services:
  certbot_ionos:
    container_name: certbot-ionos
    restart: unless-stopped
    build:
      context: .
      args:
        IMAGE_VERSION: ${CERTBOT_IMAGE_VERSION:-2026.07.16}
        VERSION: ${CERTBOT_IONOS_VERSION:-2024.11.09}
        CERTBOT_VERSION: ${CERTBOT_VERSION:-v5.7.0}
        USER_UID: ${CERTBOT_PUID:-1000}
        USER_GID: ${CERTBOT_PGID:-1000}
    image: docker-certbot-dns-ionos:${CERTBOT_IMAGE_VERSION:-2026.07.16}
    volumes:
      - ${HOME}/certbot:/certbot
      - ${HOME}/certbot/etc/letsencrypt/.secrets:/certbot/etc/letsencrypt/.secrets:ro
    environment:
      TZ: ${TZ:-Etc/UTC}
      IONOS_CREDENTIALS: /certbot/etc/letsencrypt/.secrets/ionos.ini
      IONOS_CRONTAB: ${IONOS_CRONTAB:-0 13 * * *}
      IONOS_DOMAINS: ${IONOS_DOMAINS:?Set IONOS_DOMAINS}
      IONOS_PROPAGATION: ${IONOS_PROPAGATION:-300}
      IONOS_EMAIL: ${IONOS_EMAIL:?Set IONOS_EMAIL}
      IONOS_ARGS: ${IONOS_ARGS:-}
      USER_UID: ${CERTBOT_PUID:-1000}
      USER_GID: ${CERTBOT_PGID:-1000}
